Vagrant.configure("2") do |config|
  config.disksize.size = '60GB'
  
  config.vm.define:"dev-fabric" do |cfg|
    cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.provider:virtualbox do |vb|
	  vb.name = "dev-fabric"
	  vb.customize ["modifyvm", :id, "--cpus", 2]
	  vb.customize ["modifyvm", :id, "--memory", 4096]
	end
	cfg.vm.hostname = "dev-fabric"
	cfg.vm.network "private_network", ip: "192.168.56.2"
  end
  config.vm.provision :docker
  config.vm.provision "ubuntu-package", type: "shell", path: "./hyperledger-fabric-devEnv.sh"
  
end



