Vagrant.configure("2") do |config|
  config.disksize.size = '60GB'
  config.vagrant.plugins = "vagrant-docker-compose"
  
  config.vm.define:"dev-geby" do |cfg|
    cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.provider:virtualbox do |vb|
	  vb.name = "dev-geby"
	  vb.customize ["modifyvm", :id, "--cpus", 2]
	  vb.customize ["modifyvm", :id, "--memory", 4096]
	end
	cfg.vm.hostname = "dev-geby"
	cfg.vm.network "private_network", ip: "192.168.56.2"
  end
  
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "ubuntu-package", type: "shell", path: "./ubuntu-package.sh"
  config.vm.provision "install-configuration", type: "shell", privileged: false do |s|
    s.path = "./install-configuration.sh"
  end
 
end


